GET http://localhost:8080/ca1/api/person

###
POST http://localhost:8080/ca1/api/person
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"email": "oreosermitliv@jubi.com", "firstname": "Linus", "lastname":  "Techtipz", "gender": "PC","relationshipstatus": "xD"}

###
PUT http://localhost:8080/ca1/api/person/4
Content-Type: application/json

{"email": "oreosermitliv@jubi.com", "firstname": "Linus", "lastname":  "TINUS", "gender": "PC","relationshipstatus": "xD"}

###
GET http://localhost:8080/ca1/api/person/count

###
DELETE http://localhost:8080/ca1/api/person/1

###
GET http://localhost:8080/ca1/api/person/hobby/195